services:
  postgres:
    image: postgres:15
    container_name: levelup-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: levelup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: levelup-backend
    working_dir: /app
    volumes:
      - ./backend:/app
      - /app/node_modules

    command: >
       bash -c "./wait-for-it.sh levelup-db:5432 -- ./wait-for-it.sh redis:6379 -- nodemon --legacy-watch src/index.js"  
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@levelup-db:5432/levelup?schema=public"
      REDIS_URL: "redis://redis:6379"
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000"

  redis:
    image: redis:latest
    container_name: levelup-redis
    ports:
      - "6379:6379"

       

volumes:
  postgres_data:    